# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Basalti Barbaro SRL
email: antonio@basaltibarbarosrl.it
description: > # Specialisti nella lavorazione della pietra lavica dell'Etna
 La Basalti Barbaro è azienda  leader nel settore della lavorazione della
 pietra lavica. Operiamo nel comune di Misterbianco(CT) ai piedi del vulcano
 Etna, il più grande vulcano attiv d'Europa.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aeisolution.github.io/www-basaltibarbarosrl-it/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
